// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OI.Data;

#nullable disable

namespace OI.Data.Migrations
{
    [DbContext(typeof(OiDbContext))]
    partial class OiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OI.Data.Model.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("DefaultBillingAddress1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DefaultBillingAddress1");

                    b.Property<string>("DefaultBillingAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DefaultBillingAddress2");

                    b.Property<string>("DefaultBillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DefaultBillingCity");

                    b.Property<string>("DefaultBillingStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DefaultBillingStateCode");

                    b.Property<string>("DefaultBillingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DefaultBillingZipCode");

                    b.Property<string>("DefaultShippingAddress1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DefaultShippingAddress1");

                    b.Property<string>("DefaultShippingAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DefaultShippingAddress2");

                    b.Property<string>("DefaultShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DefaultShippingCity");

                    b.Property<string>("DefaultShippingStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DefaultShippingStateCode");

                    b.Property<string>("DefaultShippingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DefaultShippingZipCode");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("Modified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("OI.Data.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("BillingAddress1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BillingAddress1");

                    b.Property<string>("BillingAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BillingAddress2");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BillingCity");

                    b.Property<string>("BillingStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("BillingStateCode");

                    b.Property<string>("BillingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BillingZipCode");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedDate");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit")
                        .HasColumnName("IsPending");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("Modified");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("OrderNumber");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Shipping");

                    b.Property<string>("ShippingAddress1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ShippingAddress1");

                    b.Property<string>("ShippingAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ShippingAddress2");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ShippingCity");

                    b.Property<string>("ShippingStateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ShippingStateCode");

                    b.Property<string>("ShippingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ShippingZipCode");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Tax");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OI.Data.Model.OrderCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("Modified");

                    b.Property<int>("NextOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("NextOrderNumber");

                    b.HasKey("Id");

                    b.ToTable("OrderCounters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0ffee00-1234-5678-abcd-ef0123456789"),
                            Created = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NextOrderNumber = 1000
                        });
                });

            modelBuilder.Entity("OI.Data.Model.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderId");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Sku");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("OI.Data.Model.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("States", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
                            Code = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678902"),
                            Code = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789003"),
                            Code = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890104"),
                            Code = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901205"),
                            Code = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012306"),
                            Code = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123407"),
                            Code = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-bcde-678901234508"),
                            Code = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-cdef-789012345609"),
                            Code = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-defa-89012345670a"),
                            Code = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-789a-efab-9012345678b0"),
                            Code = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-89ab-fabc-0123456789c1"),
                            Code = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-9abc-abcd-123456789d02"),
                            Code = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-abcd-bcde-23456789e013"),
                            Code = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-bcde-cdef-3456789f0124"),
                            Code = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-cdef-defa-456789001235"),
                            Code = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-def0-efab-567890112346"),
                            Code = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-ef01-fabc-678901223457"),
                            Code = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-f012-abcd-789012334568"),
                            Code = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            Id = new Guid("b0c1d2e3-f4a5-0123-bcde-890123445679"),
                            Code = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-1234-cdef-90123455678a"),
                            Code = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-2345-defa-0123456678b9"),
                            Code = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-3456-efab-123456789c0d"),
                            Code = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-4567-fabc-23456789d01e"),
                            Code = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-5678-abcd-3456789e012f"),
                            Code = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-6789-bcde-456789f01230"),
                            Code = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            Id = new Guid("c7d8e9f0-a1b2-789a-cdef-5678900123a1"),
                            Code = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            Id = new Guid("d8e9f0a1-b2c3-89ab-defa-678901234b52"),
                            Code = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            Id = new Guid("e9f0a1b2-c3d4-9abc-efab-789012345c63"),
                            Code = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Id = new Guid("f0a1b2c3-d4e5-abcd-fabc-890123456d74"),
                            Code = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-bcde-abcd-901234567e85"),
                            Code = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-cdef-bcde-012345678f96"),
                            Code = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-def0-cdef-1234567890a7"),
                            Code = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-ef01-defa-23456789b1b8"),
                            Code = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-f012-efab-3456789c2c09"),
                            Code = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-0123-fabc-456789d3d11a"),
                            Code = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-1234-abcd-56789e4e422b"),
                            Code = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-2345-bcde-6789f5f5533c"),
                            Code = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-3456-cdef-789006064d4d"),
                            Code = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-4567-defa-890117175e5e"),
                            Code = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-5678-efab-901228286f6f"),
                            Code = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-6789-fabc-012339397070"),
                            Code = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-789a-abcd-1234404a8181"),
                            Code = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-89ab-bcde-2345515b9292"),
                            Code = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-9abc-cdef-3456626ca3a3"),
                            Code = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-abcd-defa-456773b4b4b4"),
                            Code = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-bcde-efab-5678840c5c5c"),
                            Code = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-cdef-fabc-678995d6d6d6"),
                            Code = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-def0-abcd-7890a6e7e7e7"),
                            Code = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = new Guid("b0c1d2e3-f4a5-ef01-bcde-8901b7f8f8f8"),
                            Code = "WY",
                            Name = "Wyoming"
                        });
                });

            modelBuilder.Entity("OI.Data.Model.Order", b =>
                {
                    b.HasOne("OI.Data.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OI.Data.Model.OrderItem", b =>
                {
                    b.HasOne("OI.Data.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OI.Data.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
